/**
 * pdf-server.js
 *
 * Lightweight Express server that accepts rendered HTML from the CRM frontend
 * and returns a PDF generated by Puppeteer / Chromium.
 *
 * Run:  node server/pdf-server.js
 * Default port: 3001  (set PORT env var to override)
 *
 * The frontend posts to:  POST http://localhost:3001/generate-pdf
 * Body: { html: "<full rendered HTML string>", filename: "proposal.pdf" }
 * Response: application/pdf bytes
 */

import express from "express";
import puppeteer from "puppeteer";
import cors from "cors";

const app = express();
const PORT = process.env.PORT ?? 3001;

// Allow requests from the Vite dev server (localhost:5173) and any prod origin.
app.use(cors());
app.use(express.json({ limit: "10mb" }));

/**
 * POST /generate-pdf
 * Body: { html: string, filename?: string }
 * Returns: PDF as application/pdf
 */
app.post("/generate-pdf", async (req, res) => {
  const { html, filename = "document.pdf" } = req.body ?? {};

  if (!html || typeof html !== "string") {
    return res.status(400).json({ error: "Missing or invalid `html` field." });
  }

  let browser;
  try {
    // Resolve Chrome path — tries Puppeteer's own cache first, then
    // falls back to system Chrome (useful if Render pre-installs it).
    let executablePath;
    try {
      executablePath = puppeteer.executablePath();
      console.log("[pdf-server] Chrome path:", executablePath);
    } catch (e) {
      console.warn("[pdf-server] executablePath() failed, letting Puppeteer auto-detect:", e.message);
      executablePath = undefined;
    }

    browser = await puppeteer.launch({
      headless: "new",
      ...(executablePath ? { executablePath } : {}),
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
        "--disable-gpu",
        "--single-process",
        "--no-zygote",
      ],
    });

    const page = await browser.newPage();

    // Load the HTML directly. Using setContent with waitUntil networkidle0
    // ensures Google Fonts and any other remote assets finish loading before
    // we take the screenshot.
    await page.setContent(html, { waitUntil: "networkidle0", timeout: 30_000 });

    // Force the paper background color onto the html element via evaluate.
    // This reinforces the @page { background: #f7f5f0 } CSS rule already in
    // all templates — both mechanisms together ensure the margin strips are
    // never rendered as white by the Chromium PDF engine.
    await page.evaluate(() => {
      // Set on both html and body with !important so nothing overrides it.
      document.documentElement.style.setProperty("background-color", "#f7f5f0", "important");
      document.documentElement.style.setProperty("-webkit-print-color-adjust", "exact", "important");
      document.documentElement.style.setProperty("print-color-adjust", "exact", "important");
    });

    // Give fonts an extra moment to render (Puppeteer fires networkidle0 before
    // the browser finishes painting glyphs).
    await new Promise((r) => setTimeout(r, 500));

    const pdfBuffer = await page.pdf({
      format: "A4",

      // printBackground: true  — required for all CSS backgrounds, colors,
      // and the @page { background: #f7f5f0 } rule to be included in the PDF.
      printBackground: true,

      // preferCSSPageSize: true  — tells Chromium to honour the @page { size: A4 }
      // rule from the template CSS rather than overriding with Puppeteer's format.
      // This ensures the page dimensions exactly match what the CSS expects.
      preferCSSPageSize: true,

      // Margins match the @page { margin: 18mm 0 20mm 0 } in the templates.
      // Left/right are 0 in @page so the gold bar can bleed to the edge;
      // content padding is handled inside the template via --pad-x.
      // The Puppeteer margin here adds the physical gutter for footer clearance.
      margin: {
        top: "18mm",
        bottom: "22mm",
        left: "0",
        right: "0",
      },

      // Native Puppeteer header/footer support — no JavaScript hacks.
      // Puppeteer substitutes <span class="pageNumber"> and <span class="totalPages">
      // at render time using Chromium's built-in PDF pagination.
      displayHeaderFooter: true,

      // Header is empty — all branding lives inside the HTML template.
      headerTemplate: "<span></span>",

      // Footer: branded gold "Aurevon Studios — Confidential  |  Page X of Y"
      // Font size bumped to 10px for professional readability.
      // Color uses the document's brand gold (#c8963e) instead of muted gray.
      // Puppeteer substitutes <span class="pageNumber"> / <span class="totalPages">
      // natively — no JavaScript counting involved.
      footerTemplate: `
        <div style="
          width: 100%;
          font-family: 'Inter', Arial, sans-serif;
          font-size: 11.5px;
          color: #c8963e;
          padding: 0 15mm;
          box-sizing: border-box;
          display: flex;
          align-items: center;
          justify-content: space-between;
        ">
          <span style="color:#c8963e;font-size:11.5px;font-weight:500;letter-spacing:0.02em;">Aurevon Studios — Confidential</span>
          <span style="color:#c8963e;font-size:11.5px;">
            Page <span class="pageNumber"></span> of <span class="totalPages"></span>
          </span>
        </div>
      `,
    });

    res.set({
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Content-Length": pdfBuffer.length,
    });

    res.end(pdfBuffer);
  } catch (err) {
    console.error("[pdf-server] Generation error:", err);
    res.status(500).json({
      error: "PDF generation failed.",
      detail: err instanceof Error ? err.message : String(err),
    });
  } finally {
    if (browser) {
      await browser.close();
    }
  }
});

// Health check
app.get("/health", (_req, res) => res.json({ ok: true }));

app.listen(PORT, () => {
  console.log(`✅ pdf-server listening on http://localhost:${PORT}`);
});
