/**
 * pdf-server.js
 *
 * Lightweight Express server that accepts rendered HTML from the CRM frontend
 * and returns a PDF generated by Puppeteer / Chromium.
 *
 * Uses puppeteer-core (no bundled Chrome download) and relies on system
 * Chromium installed via the Render build command:
 *   apt-get install -y chromium-browser || apt-get install -y chromium
 *
 * Run:  node server/pdf-server.js
 * Default port: 3001  (set PORT env var to override)
 *
 * The frontend posts to:  POST /generate-pdf
 * Body: { html: "<full rendered HTML string>", filename: "proposal.pdf" }
 * Response: application/pdf bytes
 */

import express from "express";
import puppeteer from "puppeteer";
import cors from "cors";
import { existsSync } from "fs";

const app = express();
const PORT = process.env.PORT ?? 3001;

// Ordered list of Chrome/Chromium paths to try on Linux (Render free tier).
// apt-get install chromium-browser → /usr/bin/chromium-browser
// apt-get install chromium         → /usr/bin/chromium
// CHROME_PATH env var on Render dashboard overrides everything.
const SYSTEM_CHROME_PATHS = [
  process.env.CHROME_PATH,
  "/usr/bin/chromium-browser",
  "/usr/bin/chromium",
  "/usr/bin/google-chrome-stable",
  "/usr/bin/google-chrome",
  "/opt/render/project/.cache/puppeteer/chrome/linux-*/chrome-linux64/chrome",
  "/snap/bin/chromium",
];

function findChrome() {
  // 1. Explicit override from Render dashboard env vars
  if (process.env.CHROME_PATH) {
    console.log("[pdf-server] Using CHROME_PATH env:", process.env.CHROME_PATH);
    return process.env.CHROME_PATH;
  }
  // 2. Walk known system paths
  for (const p of SYSTEM_CHROME_PATHS) {
    if (existsSync(p)) {
      console.log("[pdf-server] Found Chrome at:", p);
      return p;
    }
  }
  // 3. Nothing found — throw with a helpful message
  throw new Error(
    `No Chrome/Chromium found. Checked: ${SYSTEM_CHROME_PATHS.join(", ")}. ` +
    `Set CHROME_PATH env var on Render, or add ` +
    `"apt-get install -y chromium-browser || apt-get install -y chromium" ` +
    `to your Render build command.`
  );
}

// Resolve the path once at startup so errors surface immediately.
let CHROME_EXECUTABLE;
try {
  CHROME_EXECUTABLE = findChrome();
  console.log("[pdf-server] Chrome resolved at startup:", CHROME_EXECUTABLE);
} catch (err) {
  console.error("[pdf-server] WARNING — Chrome not found at startup:", err.message);
  console.error("[pdf-server] PDF generation will fail until Chrome is installed.");
  // Don't crash the process — let /health still respond so Render doesn't
  // immediately restart the service. The real error will surface on /generate-pdf.
}

app.use(cors());
app.use(express.json({ limit: "10mb" }));

/**
 * POST /generate-pdf
 * Body: { html: string, filename?: string }
 * Returns: PDF as application/pdf
 */
app.post("/generate-pdf", async (req, res) => {
  const { html, filename = "document.pdf" } = req.body ?? {};

  if (!html || typeof html !== "string") {
    return res.status(400).json({ error: "Missing or invalid `html` field." });
  }

  // Re-resolve at request time in case CHROME_EXECUTABLE wasn't set at startup
  // (e.g. Chrome was installed after the process started — unlikely but safe).
  let executablePath;
  try {
    executablePath = CHROME_EXECUTABLE ?? findChrome();
  } catch (err) {
    return res.status(500).json({
      error: "Chrome not found.",
      detail: err.message,
    });
  }

  let browser;
  try {
    browser = await puppeteer.launch({,
      headless: true,
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        // Critical on Render: /dev/shm is very small (64MB) on free tier.
        // Without this flag Chromium crashes with "out of memory" errors.
        "--disable-dev-shm-usage",
        "--disable-gpu",
        "--single-process",
        "--no-zygote",
      ],
    });

    const page = await browser.newPage();

    await page.setContent(html, { waitUntil: "networkidle0", timeout: 30_000 });

    await page.evaluate(() => {
      document.documentElement.style.setProperty("background-color", "#f7f5f0", "important");
      document.documentElement.style.setProperty("-webkit-print-color-adjust", "exact", "important");
      document.documentElement.style.setProperty("print-color-adjust", "exact", "important");
    });

    // Extra moment for fonts to finish painting
    await new Promise((r) => setTimeout(r, 500));

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      preferCSSPageSize: true,
      margin: {
        top: "18mm",
        bottom: "22mm",
        left: "0",
        right: "0",
      },
      displayHeaderFooter: true,
      headerTemplate: "<span></span>",
      footerTemplate: `
        <div style="
          width: 100%;
          font-family: 'Inter', Arial, sans-serif;
          font-size: 11.5px;
          color: #c8963e;
          padding: 0 15mm;
          box-sizing: border-box;
          display: flex;
          align-items: center;
          justify-content: space-between;
        ">
          <span style="color:#c8963e;font-size:11.5px;font-weight:500;letter-spacing:0.02em;">Aurevon Studios — Confidential</span>
          <span style="color:#c8963e;font-size:11.5px;">
            Page <span class="pageNumber"></span> of <span class="totalPages"></span>
          </span>
        </div>
      `,
    });

    res.set({
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Content-Length": pdfBuffer.length,
    });

    res.end(pdfBuffer);
  } catch (err) {
    console.error("[pdf-server] Generation error:", err);
    res.status(500).json({
      error: "PDF generation failed.",
      detail: err instanceof Error ? err.message : String(err),
    });
  } finally {
    if (browser) {
      await browser.close();
    }
  }
});

// Health check
app.get("/health", (_req, res) => res.json({ ok: true }));

// Chrome diagnostic — visit /chrome-check to see what Chromium is resolved
app.get("/chrome-check", (_req, res) => {
  const systemPaths = SYSTEM_CHROME_PATHS.map((p) => ({
    path: p,
    exists: existsSync(p),
  }));

  let resolved = null;
  let resolveError = null;
  try {
    resolved = CHROME_EXECUTABLE ?? findChrome();
  } catch (err) {
    resolveError = err.message;
  }

  res.json({
    resolved_path: resolved,
    resolve_error: resolveError,
    env_CHROME_PATH: process.env.CHROME_PATH ?? null,
    system_paths: systemPaths,
    node_version: process.version,
    using: "puppeteer-core (no bundled Chrome)",
  });
});

app.listen(PORT, () => {
  console.log(`✅ pdf-server listening on http://localhost:${PORT}`);
});
